<template>
 <div><div class="page-heading"><div><h1>我的订单</h1><p>查看打印进度、预约信息和取件码</p></div><a-button type="primary" @click="router.push('/client/services')"><PlusOutlined /> 新建订单</a-button></div>
 <div class="surface order-filter"><a-segmented v-model:value="filter" :options="filters"/><a-button type="text" :loading="loading" @click="load"><ReloadOutlined /> 刷新</a-button></div>
 <div v-if="loading" class="loading-block"><a-spin/></div><div v-else-if="filtered.length" class="orders-list"><button v-for="order in filtered" :key="order.id" class="surface order-card" @click="router.push(`/client/orders/${order.id}`)"><div class="order-head"><span><b>订单 #{{ order.id }}</b><small>{{ formatTime(order.createTime) }}</small></span><span :class="['status-tag',`status-${order.orderStatus}`]">{{ statusText[order.orderStatus]||'未知状态' }}</span></div><div class="order-body"><div><small>打印服务</small><strong>{{ order.serviceName||'打印服务' }}</strong></div><div><small>取件门店</small><strong>{{ order.storeName||'-' }}</strong></div><div><small>预约时间</small><strong>{{ formatTime(order.appointTime) }}</strong></div><div><small>预估金额</small><strong class="price">¥{{ Number(order.totalPrice||order.servicePrice*order.pageCount*order.copies||0).toFixed(2) }}</strong></div></div><div class="order-foot"><span>{{ order.paperSize||'A4' }} · {{ order.colorMode==='COLOR'?'彩色':'黑白' }} · {{ order.duplex?'双面':'单面' }} · {{ order.pageCount||1 }}页 × {{ order.copies||1 }}份</span><RightOutlined/></div></button></div>
 <div v-else class="surface empty-state"><ShoppingOutlined style="font-size:36px;color:#bfbfbf"/><h3>暂无相关订单</h3><p>选择打印服务并上传文件后，订单会显示在这里</p><a-button type="primary" @click="router.push('/client/services')">去预约打印</a-button></div></div>
</template>
<script setup>
import { computed,onMounted,ref } from 'vue';import { useRouter } from 'vue-router';import dayjs from 'dayjs';import { PlusOutlined,ReloadOutlined,RightOutlined,ShoppingOutlined } from '@ant-design/icons-vue';import { orderApi } from '@client/api';import { useAuthStore } from '@client/stores/auth'
const router=useRouter(),auth=useAuthStore(),loading=ref(true),orders=ref([]),filter=ref('all'),filters=[{label:'全部',value:'all'},{label:'待处理',value:0},{label:'打印中',value:1},{label:'待取件',value:2},{label:'已完成',value:3},{label:'已取消',value:4}],statusText=['待处理','打印中','待取件','已完成','已取消'];const filtered=computed(()=>filter.value==='all'?orders.value:orders.value.filter(item=>item.orderStatus===filter.value));const formatTime=value=>value?dayjs(value).format('YYYY-MM-DD HH:mm'):'-'
async function load(){loading.value=true;try{orders.value=(await orderApi.getByUserId(auth.user.id)||[]).sort((a,b)=>b.id-a.id)}finally{loading.value=false}}onMounted(load)
</script>
<style scoped>
.order-filter{display:flex;align-items:center;justify-content:space-between;padding:12px 14px}.orders-list{display:grid;margin-top:12px;gap:10px}.order-card{width:100%;padding:0;text-align:left}.order-card:hover{border-color:#91caff}.order-head,.order-foot{display:flex;align-items:center;justify-content:space-between;padding:13px 16px}.order-head{border-bottom:1px solid #f0f0f0}.order-head>span:first-child{display:flex;align-items:center;gap:10px}.order-head b{color:#262626;font-size:13px}.order-head small,.order-foot{color:#8c8c8c;font-size:12px}.order-body{display:grid;padding:16px;grid-template-columns:repeat(4,1fr);gap:14px}.order-body small,.order-body strong{display:block}.order-body small{margin-bottom:5px;color:#a3a3a3;font-size:11px}.order-body strong{overflow:hidden;color:#434343;text-overflow:ellipsis;white-space:nowrap;font-size:13px}.order-body .price{color:#f5222d}.order-foot{border-top:1px solid #f0f0f0}.dark .order-head,.dark .order-foot{border-color:#303030}.dark .order-head b,.dark .order-body strong{color:rgba(255,255,255,.8)}
@media(max-width:700px){.order-filter{align-items:flex-end;gap:8px;overflow:auto}.order-body{grid-template-columns:1fr 1fr}.order-head>span:first-child{align-items:flex-start;flex-direction:column;gap:2px}.order-foot span{max-width:90%;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}}
</style>
