<template>
 <div><div class="page-heading"><div><h1>订单 #{{ route.params.id }}</h1><p>查看订单状态、文件和取件信息</p></div><a-button @click="router.push('/client/orders')"><ArrowLeftOutlined/> 返回订单</a-button></div><div v-if="loading" class="loading-block"><a-spin/></div>
 <div v-else class="detail-grid"><div class="detail-main"><section class="surface progress-section"><div class="current-status"><span :class="['status-icon',`tone-${order.orderStatus}`]"><component :is="statusIcon"/></span><div><small>当前状态</small><h2>{{ statusText[order.orderStatus]||'未知状态' }}</h2><p>{{ statusDesc[order.orderStatus] }}</p></div><a-button v-if="order.orderStatus===0" danger @click="cancelOrder">取消订单</a-button></div><a-steps :current="stepCurrent" size="small" :items="stepItems"/></section>
 <section class="surface detail-section"><h2>打印信息</h2><div class="detail-list"><div><span>打印服务</span><b>{{ order.serviceName||'-' }}</b></div><div><span>纸张规格</span><b>{{ order.paperSize||'A4' }}</b></div><div><span>色彩模式</span><b>{{ order.colorMode==='COLOR'?'彩色':'黑白' }}</b></div><div><span>单双面</span><b>{{ order.duplex?'双面':'单面' }}</b></div><div><span>页数 / 份数</span><b>{{ order.pageCount||1 }} 页 / {{ order.copies||1 }} 份</b></div><div><span>预估金额</span><b class="price">¥{{ amount }}</b></div></div></section>
 <section class="surface detail-section"><h2>打印文件</h2><div v-if="files.length" class="file-list"><div v-for="file in files" :key="file.id" class="file-row"><FileTextOutlined/><span><b>{{ file.fileName }}</b><small>{{ file.uploadTime||'已上传' }}</small></span><a-button type="link" :loading="downloading===file.id" @click="download(file)"><DownloadOutlined/> 下载</a-button></div></div><a-empty v-else description="暂无文件记录"/></section></div>
 <aside class="detail-side"><section class="surface pickup-section"><h2>取件信息</h2><div class="pickup-code"><span>取件码</span><strong>{{ order.fetchCode||'待生成' }}</strong></div><div class="side-line"><EnvironmentOutlined/><span><small>取件门店</small><b>{{ order.storeName||'-' }}</b><em>{{ order.storeAddress||'' }}</em></span></div><div class="side-line"><ClockCircleOutlined/><span><small>预约时间</small><b>{{ formatTime(order.appointTime) }}</b></span></div></section><section class="surface pickup-section"><h2>订单信息</h2><div class="compact-line"><span>排队号</span><b>{{ order.queueNumber||'-' }}</b></div><div class="compact-line"><span>创建时间</span><b>{{ formatTime(order.createTime) }}</b></div><div class="compact-line"><span>更新时间</span><b>{{ formatTime(order.updateTime) }}</b></div></section></aside></div></div>
</template>
<script setup>
import { computed,onMounted,ref } from 'vue';import { useRoute,useRouter } from 'vue-router';import { Modal,message } from 'ant-design-vue';import dayjs from 'dayjs';import { ArrowLeftOutlined,CheckCircleOutlined,ClockCircleOutlined,CloseCircleOutlined,DownloadOutlined,EnvironmentOutlined,FileTextOutlined,LoadingOutlined,PrinterOutlined } from '@ant-design/icons-vue';import { fileApi,orderApi } from '@client/api'
const route=useRoute(),router=useRouter(),loading=ref(true),order=ref({}),files=ref([]),downloading=ref(null),statusText=['待处理','打印中','待取件','已完成','已取消'],statusDesc=['门店正在确认您的打印任务','文件正在打印，请耐心等待','打印完成，请凭取件码到店领取','订单已完成','订单已取消'];const stepItems=[{title:'已提交'},{title:'打印中'},{title:'待取件'},{title:'已完成'}];const stepCurrent=computed(()=>order.value.orderStatus===4?0:Math.min(order.value.orderStatus||0,3)),statusIcon=computed(()=>[ClockCircleOutlined,LoadingOutlined,PrinterOutlined,CheckCircleOutlined,CloseCircleOutlined][order.value.orderStatus]||ClockCircleOutlined),amount=computed(()=>Number(order.value.totalPrice||order.value.servicePrice*order.value.pageCount*order.value.copies||0).toFixed(2));const formatTime=value=>value?dayjs(value).format('YYYY-MM-DD HH:mm'):'-'
async function load(){loading.value=true;try{[order.value,files.value]=await Promise.all([orderApi.getById(route.params.id),fileApi.getByOrderId(route.params.id)])}finally{loading.value=false}}
function cancelOrder(){Modal.confirm({title:'确认取消订单？',content:'只有待处理订单可以取消，取消后不可恢复。',okText:'确认取消',okType:'danger',cancelText:'暂不取消',async onOk(){await orderApi.cancel(route.params.id);message.success('订单已取消');await load()}})}
async function download(file){downloading.value=file.id;try{const blob=await fileApi.download(file.id),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=file.fileName||`file-${file.id}`;link.click();URL.revokeObjectURL(url)}finally{downloading.value=null}}
onMounted(load)
</script>
<style scoped>
.detail-grid{display:grid;grid-template-columns:minmax(0,1fr) 300px;gap:14px;align-items:start}.detail-main,.detail-side{display:grid;gap:12px}.progress-section,.detail-section,.pickup-section{padding:20px}.current-status{display:flex;align-items:center;gap:14px;margin-bottom:24px}.current-status>div{flex:1}.current-status small,.current-status p{color:#8c8c8c;font-size:12px}.current-status h2{margin:3px 0;color:#262626;font-size:18px}.status-icon{display:grid;width:48px;height:48px;place-items:center;border-radius:4px;font-size:22px}.tone-0{color:#d46b08;background:#fff7e6}.tone-1{color:#1677ff;background:#e6f4ff}.tone-2,.tone-3{color:#389e0d;background:#f6ffed}.tone-4{color:#cf1322;background:#fff1f0}.detail-section h2,.pickup-section h2{margin-bottom:16px;color:#262626;font-size:16px}.detail-list{display:grid;grid-template-columns:repeat(3,1fr);gap:18px}.detail-list span,.detail-list b{display:block}.detail-list span{margin-bottom:5px;color:#8c8c8c;font-size:11px}.detail-list b{color:#434343;font-size:13px}.detail-list .price{color:#f5222d}.file-list{display:grid;gap:8px}.file-row{display:flex;align-items:center;gap:11px;padding:10px 12px;border:1px solid #f0f0f0}.file-row>svg{color:#1677ff;font-size:20px}.file-row>span{min-width:0;flex:1}.file-row b,.file-row small{display:block}.file-row b{overflow:hidden;text-overflow:ellipsis;white-space:nowrap;font-size:13px}.file-row small{margin-top:3px;color:#a3a3a3;font-size:11px}.pickup-code{padding:16px;margin-bottom:18px;text-align:center;background:#f5f7fa}.pickup-code span,.pickup-code strong{display:block}.pickup-code span{color:#8c8c8c;font-size:11px}.pickup-code strong{margin-top:5px;color:#1677ff;font-size:28px;letter-spacing:2px}.side-line{display:flex;gap:10px;margin-top:14px}.side-line>svg{margin-top:3px;color:#1677ff}.side-line span{min-width:0}.side-line small,.side-line b,.side-line em{display:block}.side-line small{color:#a3a3a3;font-size:11px}.side-line b{margin-top:3px;font-size:13px}.side-line em{margin-top:3px;color:#8c8c8c;font-size:11px;font-style:normal}.compact-line{display:flex;justify-content:space-between;gap:12px;padding:9px 0;border-bottom:1px solid #f0f0f0;font-size:12px}.compact-line span{color:#8c8c8c}.compact-line b{text-align:right}.dark .current-status h2,.dark .detail-section h2,.dark .pickup-section h2,.dark .detail-list b{color:rgba(255,255,255,.88)}.dark .pickup-code{background:#202026}.dark .file-row,.dark .compact-line{border-color:#303030}
@media(max-width:1000px){.detail-grid{grid-template-columns:1fr}.detail-side{grid-template-columns:1fr 1fr}}@media(max-width:650px){.detail-list{grid-template-columns:1fr 1fr}.detail-side{grid-template-columns:1fr}.current-status{align-items:flex-start;flex-wrap:wrap}.current-status .ant-btn{margin-left:62px}}
</style>
