<template>
 <div><div class="page-heading"><div><h1>服务门店</h1><p>查看营业网点、服务时间与联系方式</p></div><a-button :loading="loading" @click="load"><ReloadOutlined/> 刷新</a-button></div><div v-if="loading" class="loading-block"><a-spin/></div><div v-else-if="stores.length" class="store-grid"><article v-for="store in stores" :key="store.id" class="surface store-card"><div class="store-image"><img v-if="store.imageUrl" :src="assetUrl(store.imageUrl)" :alt="store.name"/><div v-else><ShopOutlined/></div><a-tag color="success">营业中</a-tag></div><div class="store-content"><h2>{{ store.name }}</h2><p><EnvironmentOutlined/> {{ store.address||'地址待完善' }}</p><div class="store-meta"><span><ClockCircleOutlined/> {{ store.hours||'营业时间请咨询门店' }}</span><span><PhoneOutlined/> {{ store.phone||'暂无电话' }}</span></div><div class="store-services"><a-tag v-for="item in parseServices(store.services)" :key="item">{{ item }}</a-tag></div><a-button type="primary" block @click="router.push('/client/services')">选择该门店附近的服务</a-button></div></article></div><div v-else class="surface empty-state"><ShopOutlined style="font-size:36px;color:#bfbfbf"/><h3>暂无营业门店</h3><p>门店恢复营业后会显示在这里</p></div></div>
</template>
<script setup>
import { onMounted,ref } from 'vue';import { useRouter } from 'vue-router';import { ClockCircleOutlined,EnvironmentOutlined,PhoneOutlined,ReloadOutlined,ShopOutlined } from '@ant-design/icons-vue';import { storeApi } from '@client/api';const router=useRouter(),stores=ref([]),loading=ref(true);const parseServices=value=>(value||'文档打印,照片冲印').split(',').map(x=>x.trim()).filter(Boolean);const assetUrl=url=>/^https?:\/\//.test(url||'')?url:(url?.startsWith('/api/')?url:`/api/print${url}`);async function load(){loading.value=true;try{stores.value=await storeApi.getActive()||[]}finally{loading.value=false}}onMounted(load)
</script>
<style scoped>
.store-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:12px}.store-card{overflow:hidden}.store-image{position:relative;height:150px;background:#eef3f8}.store-image img{width:100%;height:100%;object-fit:cover}.store-image>div{display:grid;height:100%;place-items:center;color:#91a3b5;font-size:38px}.store-image .ant-tag{position:absolute;top:10px;right:8px}.store-content{padding:16px}.store-content h2{color:#262626;font-size:16px}.store-content>p{min-height:40px;margin-top:7px;color:#8c8c8c;font-size:12px;line-height:1.6}.store-meta{display:grid;margin:12px 0;gap:6px;color:#595959;font-size:11px}.store-services{min-height:31px;margin-bottom:12px}.dark .store-content h2{color:rgba(255,255,255,.88)}.dark .store-image{background:#202026}.dark .store-meta{color:rgba(255,255,255,.55)}@media(max-width:1050px){.store-grid{grid-template-columns:repeat(2,1fr)}}@media(max-width:600px){.store-grid{grid-template-columns:1fr}}
</style>
